### ISSUE TITLE
PauliStrings operator in VMC mode returning the wrong answer  

### ISSUE THREAD

**Issue by kastoryano** [netket/netket#455] opened 2020-07-31 07:18 UTC
This simple example constructs the transverse field Ising model using the PauliStrings operator. Exact diagonalization returns the right answer, but the vmc method does not (using the v3.0 branch). 

```
import numpy as np
import netket as nk

#Construct the hamiltonian:
# H=- (Z1 Z2+ Z2 Z3 +Z3 Z4 + Z1 Z4) -(X1 X2+X3+X4)

ha = nk.operator.PauliStrings(operators=['ZZII','IZZI','IIZZ','ZIIZ','XIII','IXII','IIXI','IIIX'], weights=[-1,-1,-1,-1,-1,-1,-1,-1])

#graph object
g = nk.graph.Hypercube(length=4, n_dim=1, pbc=True)

# Spin based Hilbert Space
hi = nk.hilbert.Spin(s=0.5, graph=g)

# Restricted Boltzmann Machine
ma = nk.machine.RbmSpin(alpha=3, hilbert=hi)
ma.init_random_parameters(seed=1234, sigma=0.01)


# Metropolis Local Sampling
sa = nk.sampler.MetropolisLocal(ma, n_chains=32)

# Optimizer
op = nk.optimizer.Sgd(ma, learning_rate=0.1)

# Stochastic Reconfiguration
sr = nk.optimizer.SR(ma, diag_shift=0.1)

# Create the optimization driver
gs = nk.Vmc(hamiltonian=ha, sampler=sa, optimizer=op, n_samples=1000, sr=sr)

# Run the optimization for 300 iterations
gs.run(n_iter=50, out="test")

#Exact diagonalization
res = nk.exact.lanczos_ed(ha, first_n=1, compute_eigenvectors=False)
print("Exact transverse Ising ground state energy = {0:.3f}".format(res.eigenvalues[0]))
```

**Comment by gcarleo** [comment] 2020-07-31 10:03
The issue is that PauliStrings assumes a Qubit Hilbert space ,i.e. 0 and 1
local numbers,but instead here you are using Spin,which has +/-1 local
numbers. This means that most likely something goes wrong when computing
the interactions in the vmc. You can retrieve the Hilbert space of
PauliStrings doing pauli_hamiltonian.hilbert, or you can maybe stick to
spins but add some constants shifts to the PauliStrings to make it
compatible with the -1,1 local basis

**Comment by kastoryano** [comment] 2020-07-31 11:18
Thanks! Actually just replacing `hi = nk.hilbert.Spin(s=0.5, graph=g)` by `hi = nk.hilbert.Qubit( graph=g)` does the job.

**Comment by PhilipVinc** [comment] 2020-07-31 13:00
Still this is a bug on our part and we should fix it.

**Comment by gcarleo** [comment] 2020-07-31 14:16
Changing this to error checking issue since it is not a bug per se, we should just check that we use consistent hilbert spaces in the sampler

**Comment by PhilipVinc** [comment] 2021-12-06 20:23
Closed by several PRs that I can't recall anymore.

This will now error.

**Closed by PhilipVinc** 2021-12-06 20:23 UTC
Labels: error checking
