### ISSUE TITLE
Regularization isssue in mc_stats.py

### ISSUE THREAD

**Issue by kastoryano** [netket/netket#459] opened 2020-08-04 05:47 UTC
NetKet v3.0
I am running into a recurrent problem with mc_stats. Seems to be a regularization issue:

```
/home/ec2-user/my_app/env3/lib64/python3.7/site-packages/netket-3.0-py3.7.egg/netket/stats/mc_stats.py:160: RuntimeWarning: divide by zero encountered in true_divide
 95%|▉| 285/300 [00:39<00:01,  7.83it/s, Energy=-1.0943+0.0000j ± 0.00096 [var=1.1e-03, R_hat=/home/ec2-user/my_app/env3/lib64/python3.7/site-packages/netket-3.0-py3.7.egg/netket/stats/mc_stats.py:12: RuntimeWarning: divide by zero encountered in log10
 95%|▉| 285/300 [00:39<00:02,  7.17it/s, Energy=-1.0943+0.0000j ± 0.00096 [var=1.1e-03, R_hat=
Traceback (most recent call last):
  File "H2_test.py", line 101, in <module>
    gs.run(n_iter=300, out="test")
  File "/home/ec2-user/my_app/env3/lib64/python3.7/site-packages/netket-3.0-py3.7.egg/netket/abstract_variational_driver.py", line 234, in run
  File "/home/ec2-user/my_app/env3/lib64/python3.7/site-packages/netket-3.0-py3.7.egg/netket/stats/mc_stats.py", line 46, in __repr__
  File "/home/ec2-user/my_app/env3/lib64/python3.7/site-packages/netket-3.0-py3.7.egg/netket/stats/mc_stats.py", line 12, in _format_decimal
OverflowError: cannot convert float infinity to integer
```

Note: switching to `show_progress=False` in `.run` does not remove the error.

**Comment by gcarleo** [comment] 2020-08-04 16:00
Does this produce a fatal error and exits or is it just a warning?

**Comment by kastoryano** [comment] 2020-08-04 17:19
The last one is fatal and causes it to exit

**Comment by gcarleo** [comment] 2020-08-04 19:58
@femtobit might know better why this happens?

**Comment by femtobit** [comment] 2020-08-04 20:35
@gcarleo Indeed, there is an error in the code for printing the stats when `error_of_mean` is infinite. While this is of course and indication, that something went wrong during VMC sampling, this expedition should still not happen. I've created PR #460 which should resolve this.

While this should resolve the immediate issue, I think it would be good to find out where the infinite error in the VMC result comes from and whether this is a numerical bug in the VMC code or pathological behavior of the sampling caused by the specific state.

**Comment by gcarleo** [comment] 2020-08-04 21:27
Thanks @femtobit for fixing this! Yes, an infinite error of mean is certainly something fishy, it might come from a wrong/unreliable estimation of the correlation times, but it's hard to say... maybe it will be good to check at some point if the autocorrelation time can accidentally become exactly zero (it shouldn't really be smaller than 1 though)

**Comment by femtobit** [comment] 2020-08-04 21:33
> It might come from a wrong/unreliable estimation of the correlation times, but it's hard to say...

It would be good to check were the infinity comes from. It might already be in the data (i.e., the local values) - given that the probability ratio enters there, a local value might overflow if the configurations involved have drastically different probabilities.

**Comment by kastoryano** [comment] 2020-08-06 09:33
The latest push has not solved the problem for me: 

```
  File "/home/ec2-user/my_app/env4/lib64/python3.7/site-packages/netket-3.0-py3.7.egg/netket/abstract_variational_driver.py", line 234, in run
  File "/home/ec2-user/my_app/env4/lib64/python3.7/site-packages/netket-3.0-py3.7.egg/netket/stats/mc_stats.py", line 46, in __repr__
  File "/home/ec2-user/my_app/env4/lib64/python3.7/site-packages/netket-3.0-py3.7.egg/netket/stats/mc_stats.py", line 12, in _format_decimal
OverflowError: cannot convert float infinity to integer
```

Something strange is happening, as the error to the mean is pretty stable (by eyeballing) before the error message is output.

**Comment by femtobit** [comment] 2020-08-06 11:36
@kastoryano Thanks for reporting back!

I think the I see the issue now: The error of the mean is not, in fact, too large here, but conversely it looks like it is too close to zero. Then, the formula for estimating the number of decimals to show can still overflow because `log10(error)` becomes infinite.

This should be fixed by the changes in PR #461 now.

**Comment by gcarleo** [comment] 2020-08-11 15:24
This is solved now?

**Comment by femtobit** [comment] 2020-09-07 11:02
> This is solved now?

I think so.

**Closed by femtobit** 2020-09-07 11:02 UTC
