### ISSUE TITLE
Modeling Quantum States with Broken Symmetries

### ISSUE THREAD

**Issue by chrisrothUT** [netket/netket#658] opened 2021-04-26 23:04 UTC
We now have the models RBMSymm and GCNN that can learn the wavefunction of the lowest-lying symmetric energy level. As @attila-i-szabo and i discussed today, it would be really nice to be able to explore broken symmetry states as well. We need two things:

a) A layer that does a phase-weighted average over the output (pre-averaging) of a GCNN or RBMSymm using the desired character of the symmetry group. This should be straightforward to implement.

b) A method for generating the character of the symmetry group by specifying eigenvalues w.r.t to symmetry operations.( I.e. specify the character table for p4 by specifying R(\pi/4) and T(1,0) and T(0,1) )

There's a few ways to go about b). 

We could try to make lattice (or graph) generate a labelled SymmGroup (this may or may not be useful [https://networkx.org/documentation/stable/reference/algorithms/isomorphism.ismags.html]) instead of randomly arranged isomorphisms. Any ideas @VolodyaCO?

We could also work with the algebraic group (instead of the graph) and try to generate the cosets from that. This may not produce the cosets we want, but we can still use it to look for valid character tables. This would require some work from the user to figure out what these character tables mean.

**Comment by attila-i-szabo** [comment] 2021-04-27 10:35
As for labelling `SymmGroup` using NetworkX, I think `ISMAGS.analyze_symmetry` probably does what we need, but the documentation is too cryptic to make use of it, so [I asked them what it means.](https://github.com/networkx/networkx/discussions/4761) No useful replies yet, but you might want to keep an eye on it.

In any case, an automated approach like this will only ever return the generators of the SymmGroup at best, so the user will have to figure out what those mean...

**Comment by PhilipVinc** [comment] 2021-04-27 13:26
By the way, it looks like `nauty and traces` https://pallini.di.uniroma1.it/Introduction.html can produce a canonical labelling. mayb eit can also generate the characters?

**Comment by chrisrothUT** [comment] 2021-04-27 16:20
Thanks so much! Right now my computer is out of commission but I will get to this in the near future.

**Comment by attila-i-szabo** [comment] 2021-04-27 20:11
> Also relevant, https://github.com/gap-system, which implements nauty and traces algorithms...
> 
> See for example https://www.gap-system.org/Manuals/doc/ref/chap40.html#X81FC3CEF85CED3DC

Thanks for the pointer! The link is not about what we're looking for (it's _group_ homomorphisms), but nauty and traces are indeed implemented for GAP, see https://www.gap-system.org/Manuals/pkg/digraphs/doc/chap7.html#X858C32127A190175 

What's still missing from this is a "nice presentation" of the group, and it's not clear to me how much that can be automated. However, I think [this](https://math.stackexchange.com/questions/1618446/how-can-i-display-generators-or-a-minimal-generating-set-with-gap) gets pretty close to it, though I'd have to investigate what the output of `MinimalGeneratingSet` would look like on an automorphism group from the above code.
 
> EDIT: Asking away in the Julia slack people tell me that the character table is definitely doable in GAP.

Again, I'm sure this is doable, there's a [whole chapter](https://www.gap-system.org/Manuals/doc/ref/chap71.html) of docs on it, the problem is that the raw character table of a big group (like the wallpaper group of a large lattice) is not very edifying, you'd like to label it by wave vector-little group combinations so much as it's possible.

The last question is how we'd integrate all this with NetKet (other than the communicate-via-files solution, which I'm happy with, but it might not be the most elegant)

**Comment by chrisrothUT** [comment] 2021-04-27 22:01
I don’t think there’s a good way to solve this problem unless we find a way for Lattice.py to generate the graph and all of it’s automorphisms.

I do think that just generating the raw character table is useful in and of itself. The user has some work to do in figuring out which representation is the one they want, but I think a lot of it can be done by counting eigenvalues. 

If we combined the functionality of a) Having readable symmetry group for a few common lattices b) If your lattice isn’t in that group you can still generate the character tables and try a bunch of different representations, that might be good for now. Maybe I’m just unambitious :)

**Comment by PhilipVinc** [comment] 2021-04-27 22:27
Guys I think the discussion on this is interesting but that messages on GitHub are kind of slow. Do you want to hop on a zoom/Skype/slack/whatever meeting on Thursday let’s say 4pm Paris time to discuss this a bit further?
Il 28 apr 2021, 00:01 +0200, chrisrothUT ***@***.***>, ha scritto:

**Comment by chrisrothUT** [comment] 2021-04-27 23:09
That works for me

**Comment by PhilipVinc** [comment] 2021-04-28 14:52
Friday 4 pm paris time?

**Comment by attila-i-szabo** [comment] 2021-04-28 16:45
Good for me!

**Comment by chrisrothUT** [comment] 2021-04-28 17:08
Works for me as well

**Comment by attila-i-szabo** [comment] 2021-04-28 17:12
Great, I'll make a zoom meeting and email the link to you later today

**Comment by femtobit** [comment] 2021-04-28 21:45
Great discussion! Would you mind also sending me an invite for Friday? Extending our symmetry handling capabilities is relevant to me as well and I'd like to discuss what we can do based on our new interface, also with regard to adding character tables.

**Comment by attila-i-szabo** [comment] 2021-04-28 21:48
Sure! Can you give me an email I can send it to? I'm not a fan of putting zoom links on public websites ;-)

**Comment by femtobit** [comment] 2021-04-28 21:59
@attila-i-szabo Great, thanks! You can use my email address from here: https://www.mpsd.mpg.de/person/101180/2736

**Comment by attila-i-szabo** [comment] 2021-04-30 10:52
In preparation for today, I checked out what the graph/group algorithms in GAP can do for us. Unfortunately, its strategy for finding simple presentations of groups is a bit too clever for us...
```
gap> graph := Digraph([[2,3,4,7],[1,3,5,8],[1,2,6,9],[5,6,1,7],[4,6,2,8],[4,5,3,9],[8,9,1,4],[7,9,2,5],[7,8,3,6]]);
<immutable digraph with 9 vertices, 36 edges>
gap> grp := AutomorphismGroup(graph);
Group([ (2,3)(5,6)(8,9), (2,4)(3,7)(6,8), (1,2)(4,5)(7,8) ])
gap> Size(grp);
72
gap> MinimalGeneratingSet(grp);
[ (2,4)(3,7)(6,8), (1,6,7,3,4,9)(2,5,8) ]
gap> Display(CharacterTable(grp));
CT1

     2  3  2  3  2  2  1  1  1  1
     3  2  1  .  1  .  2  1  1  2

       1a 2a 2b 2c 4a 3a 6a 6b 3b
    2P 1a 1a 1a 1a 2b 3a 3a 3b 3b
    3P 1a 2a 2b 2c 4a 1a 2a 2c 1a
    5P 1a 2a 2b 2c 4a 3a 6a 6b 3b

X.1     1  1  1  1  1  1  1  1  1
X.2     1 -1  1 -1  1  1 -1 -1  1
X.3     1 -1  1  1 -1  1 -1  1  1
X.4     1  1  1 -1 -1  1  1 -1  1
X.5     2  . -2  .  .  2  .  .  2
X.6     4 -2  .  .  .  1  1  . -2
X.7     4  .  . -2  . -2  .  1  1
X.8     4  .  .  2  . -2  . -1  1
X.9     4  2  .  .  .  1 -1  . -2
```
The first line creates a 3x3 square lattice with periodic boundary conditions. Its automorphism group has the expected 8x9=72 elements, but as it turns out, it can be written a bit too succinctly for our purposes (the first presentation is two vertical and one diagonal mirrors, the second is the same diagonal mirror and a vertical glide). 
Likewise, we can generate character tables too: it's easy to discover the character table of D_8 in the output, but I'm not sure how to attach physical meaning to the remaining 4-dimensional irreps (i.e., I know where they come from, but not sure how to label them with things like wave vectors).

**Comment by chrisrothUT** [comment] 2021-04-30 14:18
I was wondering why you had twice the edges, but apparently that is what is typically done for symmetric graphs.

Does Digraph take a list of edges? That is how we usually specify graphs in Netket. I think there’s a straightforward mapping to complex numbers but we still have the issue of figuring out which elements of automorphisms() correspond to particular symmetry elements.

**Comment by attila-i-szabo** [comment] 2021-04-30 14:21
@chrisrothUT are you coming on Zoom?

**Comment by attila-i-szabo** [comment] 2021-04-30 17:35
Digraph is short for directed graph, you have to list the edges both ways. It can be constructed with a list of edges, but the docs were a bit cryptic

**Comment by attila-i-szabo** [comment] 2021-05-01 16:59
As for the group theory notes, what would be the preferred format? I'm tempted to use LaTeX because there will be a lot of maths, but that wouldn't play nicely with the existing docs/tutorials. Github's maths-free MD on the other hand won't really cut it.

Also, would you like these notes as part of the NetKet docs or just FYI?

**Comment by PhilipVinc** [comment] 2021-05-03 06:47
>As for the group theory notes, what would be the preferred format?

What you feel comfortable in.
I personally dislike (restructured text) `.rst` and prefer Markdown, which is a lightweight latex. The last pages I added to the docs are already written in [Markdown (MyST dialect)](https://myst-parser.readthedocs.io/en/latest/using/syntax.html#math-shortcuts) and it will almost look like LaTeX because you can use inline math $$ and block-math $$\begin{equation} \end{equation} $$.

> Also, would you like these notes as part of the NetKet docs or just FYI?

I would personally be interested myself in reading them, but I think adding those to the docs would be a great addition, as it's quite related.

**Comment by attila-i-szabo** [comment] 2021-05-03 10:10
> > As for the group theory notes, what would be the preferred format?
> 
> What you feel comfortable in.
> I personally dislike (restructured text) `.rst` and prefer Markdown, which is a lightweight latex. The last pages I added to the docs are already written in [Markdown (MyST dialect)](https://myst-parser.readthedocs.io/en/latest/using/syntax.html#math-shortcuts) and it will almost look like LaTeX because you can use inline math $$ and block-math $$\begin{equation} \end{equation} $$.

Cool, I'd prefer MD for the plain text bits too, and I guess it's github's problem they don't support TeX :-)

> > Also, would you like these notes as part of the NetKet docs or just FYI?
> 
> I would personally be interested myself in reading them, but I think adding those to the docs would be a great addition, as it's quite related.

OK, I'm basically asking if I should submit them as a PR if it's done. Is `docs/docs` a good place to put it?

**Comment by PhilipVinc** [comment] 2021-05-03 17:22
Yes. You then must 'hook it up' by putting the file name inside of a relevant section in `docs/index.rst` to make it appear in the sidebar

**Comment by attila-i-szabo** [comment] 2021-05-11 08:29
> The advantage is we would compose the eigenvalues as we compose the SymmGroup.

That's not an advantage, the space group is never a direct product of these terms, so this construction would almost always return invalid characters. 

> Better option might be to have a new class say SymmetryEigvals that includes a SymmGroup and a list of eigvals.

Indeed. I think the user can't really be spared from specifying the full character for the point group at least (we can make a default for the trivial character though), but then we can take care of constructing the character for the full space group using the algorithm in #700

**Comment by PhilipVinc** [comment] 2021-12-06 20:19
Closed by a series of countless PR (though a tutorial would still be nice...)

**Closed by PhilipVinc** 2021-12-06 20:19 UTC
